version: "3.7"

services:
  app:
    build: .

  db:
    image: "ibmcom/db2:latest"
    privileged: true
    ports:
      - "50000:50000"
    volumes:
      - ./db:/database
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=password123
      - DB2INSTANCE=db2
      - DBNAME=testdb
